# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cad3f7ba25dafe15eb8f2305f5419ec09738009f2cce08085cd4371bd1c9c379ed8a30d9795e8973ee07bce3f3002be3b65a0ba12070ed071b7bb5163d5ca822

test:
  secret_key_base: b9c34ab477368d956252a8298e03aefe1b0ca2fb3f7bf68892fd110ac0f79cb6ffe0220b3327505dc38d9ab191300b9e4d16dde98a6090c4d1cbd2cb92bd77c0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
